CREATE DATABASE IF NOT EXISTS POKEMON;
USE POKEMON;

CREATE TABLE TIPO_MONTARIA (
    ID_TIPO_MONTARIA INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(40) NOT NULL
);

CREATE TABLE TIPO_ITEM (
    ID_TIPO_ITEM INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(40) NOT NULL
);

CREATE TABLE TIPO_POKEMON (
    ID_TIPO_POKEMON INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(40) NOT NULL
);

CREATE TABLE STATUS (
    ID_STATUS INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(40) NOT NULL
);

CREATE TABLE NATURE (
    ID_NATURE INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(40) NOT NULL
);

CREATE TABLE TIPO_MOVES (
    ID_TIPO_MOVES INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(40) NOT NULL
);

CREATE TABLE MONTARIA (
    ID_MONTARIA INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(40) NOT NULL,
    TIPO_MONTARIA INT NOT NULL,
    FOREIGN KEY (TIPO_MONTARIA) REFERENCES TIPO_MONTARIA(ID_TIPO_MONTARIA)
);

CREATE TABLE ITEM (
    ID_ITEM INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(40) NOT NULL,
    ID_TIPO_ITEM INT NOT NULL,
    FOREIGN KEY (ID_TIPO_ITEM) REFERENCES TIPO_ITEM(ID_TIPO_ITEM)
);

CREATE TABLE MOVES (
    ID_MOVES INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(40) NOT NULL,
    TIPO INT NOT NULL,
    FOREIGN KEY (TIPO) REFERENCES TIPO_MOVES(ID_TIPO_MOVES)
);

CREATE TABLE PERSONAGEM (
    ID_PERSONAGEM INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    SEXO CHAR(1) NOT NULL,
    ID_MONTARIA INT NOT NULL,
    FOREIGN KEY (ID_MONTARIA) REFERENCES MONTARIA(ID_MONTARIA)
);

CREATE TABLE POKEMONS (
    ID_POKEMON INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(40) NOT NULL,
    TIPO1 INT NOT NULL,
    FOREIGN KEY (TIPO1) REFERENCES TIPO_POKEMON(ID_TIPO_POKEMON),
    TIPO2 INT NOT NULL,
    FOREIGN KEY (TIPO2) REFERENCES TIPO_POKEMON(ID_TIPO_POKEMON),
    STATUS INT NOT NULL,
    FOREIGN KEY (STATUS) REFERENCES STATUS(ID_STATUS),
    NATURE INT NOT NULL,
    FOREIGN KEY (NATURE) REFERENCES NATURE(ID_NATURE),
    ACESSORIO INT NOT NULL,
    FOREIGN KEY (ACESSORIO) REFERENCES ITEM(ID_ITEM),
    MOVE INT NOT NULL,
    FOREIGN KEY (MOVE) REFERENCES MOVES(ID_MOVES),
    DESCRICAO VARCHAR(150) NOT NULL
);

CREATE TABLE EQUIPE (
    ID_PERSONAGEM INT NOT NULL,
    FOREIGN KEY (ID_PERSONAGEM) REFERENCES PERSONAGEM(ID_PERSONAGEM),
    ID_POKEMON INT NOT NULL,
    FOREIGN KEY (ID_POKEMON) REFERENCES POKEMONS(ID_POKEMON)
);

CREATE TABLE INVENTARIO (
    ID_PERSONAGEM INT NOT NULL,
    FOREIGN KEY (ID_PERSONAGEM) REFERENCES PERSONAGEM(ID_PERSONAGEM),
    ID_ITEM INT NOT NULL,
    FOREIGN KEY (ID_ITEM) REFERENCES ITEM(ID_ITEM)
);